### ISSUE TITLE
Create better process for testing locally & end-to-end

### ISSUE THREAD

**Issue by matthewwong525** [fleetingnotes/fleeting-notes-plugins#12]
Problem:
- Right now it's difficult to test the plugin end-to-end without merging to main?
- also local testing is kind of a pain, especially since a webserver file needs to be created for each folder.

Suggested Solution:
- Create a `plugins/test` folder for testing purposes.  And maybe set up pipelines to allow for whatever changes to go in here. In UI 
- Create a `test_webserver.ts` file that is similar to [webserver.ts](https://github.com/fleetingnotes/fleeting-notes-plugins/blob/main/webserver.ts) that can be run locally without the restrictions of the .env file (also doesn't call posthog / supabase)

**Comment by gonzalovelasco** [comment]
I was thinking in create integrations tests for the plugins. https://deno.com/manual@v1.34.1/basics/testing

**Comment by matthewwong525** [comment]
> I was thinking in create integrations tests for the plugins. https://deno.com/manual@v1.34.1/basics/testing and we can run the tests in the github CI

@gonzalovelasco i love that you love tests. I'll create a ticket and this is something we can work on next week :)

**Comment by matthewwong525** [comment]
Duplicate of #16 #13
